name: CI - Testes e Alerta Discord

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar testes
        run: pytest

      - name: Enviar alerta para Discord
        if: always()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            STATUS="SUCESSO"
          else
            STATUS="FALHA"
          fi
          curl -H "Content-Type: application/json" \
            -d "{\"content\":\":robot: Workflow finalizado com status: $STATUS\nRepositório: ${{ github.repository }}\nBranch: ${{ github.ref_name }}\nAutor: ${{ github.actor }}\"}" \
            $DISCORD_WEBHOOK
